### ISSUE TITLE
这个readme看的云里雾里的

### ISSUE THREAD

**Issue by Ivorzk** [wwog/wechat-pay-v3-sdk#1]
初始化配置我倒是看懂了，没看懂怎么用我可以把它理解为，一个帮忙做了一个接口签名的工具么？除了接口签名以外，别的还做了什么？
没看懂文档，请求方式也没看懂是怎么请求的

**Comment by wwog** [comment]
调用你可以直接new也可以使用封装的容器。假设你需要使用小程序支付,可以看支持功能列表,对应库名MiniProgramPay。那么你可以`new MiniProgramPay(new WechatPayV3Base({xxx})).order({xxx})`也可以使用我提供的容器`apiController({xxx}).use(MiniProgramPay).order({xxx})`

**Comment by Ivorzk** [comment]
好的，昨晚我被那个证书序列号差点搞死了，最后无奈之下，去研究了一下这个仓库的源码，弄是弄通了，持续使用一段时间再看看有没有什么问题，感谢楼主提供的sdk。

**Comment by wwog** [comment]
容器调用保持单例,可以轻松的对接服务,不需要管理。容器函数提供了自动的依赖注入,你手动new需要传入基础类的实例。其他库大多是继承一个提供了基础方法的类，为什么不直接继承基础类，一旦封装不同类型的功能类，每次去new 功能类，就新开了一个实例且这个实例继承了完整的基础类。性能不好,所以采用依赖注入。提供容器是为了能直接保持优越的性能。也没心智负担。

**Comment by wwog** [comment]
嗯,有什么问题可以问。我是实际项目生产环境在使用。不过只接入了商户进件和小程序支付。但其余都是简单的接口地址替换，应该不会有什么问题。有问题可以提出来。
