### ISSUE TITLE
退款的接口定义不对

### ISSUE THREAD

**Issue by lxb365** [wwog/wechat-pay-v3-sdk#2]
export interface Refund_Business {
  /** 微信支付订单号 */
  transaction_id?: string
  /** 商户订单号 */
  out_trade_no?: string
  /** 商户退款单号 */
  out_refund_no: string
  /** 退款原因 */
  reason?: string
  /** 退款结果通知url */
  notify_url?: string
  /** 资金账户 */
  funds_account?: string
  /** 单品列表信息，微信支付后台会根据此参数控制向用户展示商品详情 */
  goods_detail?: GoodsDetail[]
}

这个接口和微信支付的退款接口定义不一致，没有amount

**Comment by wwog** [comment]
已更改
